This is makeindex, version 2.16 [MiKTeX 22.3].
Scanning style file ./thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (191 entries accepted, 0 rejected).
Sorting entries.....done (1598 comparisons).
Generating output file thesis.acr....done (122 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
