This is makeindex, version 2.16 [MiKTeX 22.7.30].
Scanning style file ./thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (244 entries accepted, 0 rejected).
Sorting entries.....done (2187 comparisons).
Generating output file thesis.acr....done (146 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
